name: CloudDrive CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download Source Code via API Zip
      run: |
        curl -L -o repo.zip "https://github.com/AryanPatel2106/clouddrive/archive/refs/heads/main.zip"
        unzip repo.zip
        mv clouddrive-main/* ./
        rm -rf clouddrive-main repo.zip

    - name: Pack Application Code
      run: |
        tar -czf clouddrive-latest.tar.gz server.js package.json package-lock.json deploy.sh pull-updates.sh

    - name: Upload Artifact to AWS S3 (Native Sync)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1
      run: |
        aws s3 cp clouddrive-latest.tar.gz s3://clouddrive-deploy-bucket-2026/clouddrive-latest.tar.gz